<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>ERPZen</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERPZen.Domain\ERPZen.Domain.csproj" />
    <ProjectReference Include="..\ERPZen.Application.Contracts\ERPZen.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Account.Application" Version="9.3.3" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="9.3.3" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="9.3.3" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="9.3.3" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="9.3.3" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="9.3.3" />
  </ItemGroup>

</Project>
